<script type="text/javascript" charset="utf-8">
jQuery(document).ready(function () {
    Omeka.addReadyCallback(Omeka.LocalContexts.addHideButtons);
});
</script>
<fieldset id="item-local-contexts-fields">
<h2><?php echo __('Local Contexts'); ?></h2>
<p class='explanation'><?php echo __('Assign selected Local Contexts value(s) to selected metadata element in selected language(s)'); ?>
<div class="field">
    <label class="two columns alpha"><?php echo __('Metadata element'); ?></label>
    <div class="inputs five columns omega">
        <?php echo $this->formSelect('custom[lc_content_element]', null, array(), $elementData); ?>
    </div>
</div>
<div class="field">
    <label class="two columns alpha"><?php echo __('Local Contexts language(s)'); ?></label>
    <div class="inputs five columns omega">
        <?php echo $this->formSelect('custom[lc_content_language]', null, array(), $lcLanguageOptions); ?>
    </div>
</div>
<div class="field">
    <label class="two columns alpha"><?php echo __('Local Contexts value(s)'); ?></label>
    <div class="inputs five columns omega local-contexts-multicheckbox">
    <?php foreach ($this->lcBatchContent as $project): ?>
        <div class='local-contexts-multicheckbox-row'>
            <input type='checkbox' name='custom[lc_content][]' value='<?php echo  __(json_encode($project['value'])); ?>' aria-labelledby="local-context-notice-label">
            <div class='column content'>
            <?php echo $project['label']; ?>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
</div>
</fieldset>
