<div class="field">
    <div class="field-meta seven columns alpha">
        <label><?php echo __('Local Contexts Notices'); ?></label>
    </div>
    <div class="inputs localcontexts seven columns omega">
        <?php
        echo "<p class='explanation'>" . __('Assign selected Local Contexts notice(s) to selected metadata element in selected language(s) from dropdown menus.') . "</p>";
        echo "<div class='input-block'>";
        echo $this->formSelect('lc_content_element', null, null, $element_data);
        echo $this->formSelect('lc_content_language', null, null, $language_data);
        $html = '';
        foreach ($this->lc_content as $notice_content) {
            $html .= "<div class='label admin'>";
            $html .= "<div class='column check'><input type='checkbox' name='lc-content[]' value='" . __(json_encode($notice_content)) . "'></div>";
            $html .= "<div class='column content'>";
            if (isset($notice_content['project_url'])) {
                $html .= "<a class='name' target='_blank' href=" . $notice_content['project_url'] . ">" . $notice_content['project_title'] . "</a>";
            }
            foreach($notice_content as $key => $content) {
                if (is_int($key)) {
                    $html .= "<div class='column description'>";
                    $html .= "<img class='column image' src='" . $content['image_url'] . "'>";
                    $html .= "<div class='column text'><div class='name'>" . $content['name'];
                    if (isset($content['language'])) {
                        $html .= "<span class='language'> (" . $content['language'] . ")</span>";
                    }
                    $html .= "</div>";
                    $html .= "<div class='description'>" . $content['text'] . "</div></div></div>";
                }
            }
            $html .= "</div></div>"; 
        }
        echo $html;
        echo "</div>";
        ?>
    </div>
</div>
