<div class="field">
    <div class="field-meta seven columns alpha">
        <label><?php echo __('Local Contexts Notices'); ?></label>
    </div>
    <div class="inputs localcontexts seven columns omega">
        <p class='explanation'><?php echo __('Assign selected Local Contexts notice(s) to selected metadata element in selected language(s)'); ?></p>
        <div class='input-block'>
        <?php echo $this->formSelect('lc_content_element', null, null, $element_data); ?>
        <?php echo $this->formSelect('lc_content_language', null, null, $language_data); ?>
        <?php foreach ($this->lc_content as $notice_content): ?>
            <div class='local-contexts-input'>
                <div class='column check'><input type='checkbox' name='lc_content[]' value='<?php echo  __(json_encode($notice_content)); ?>'></div>
                <div class='column content'>
                <?php if (isset($notice_content['project_url'])): ?>
                    <a class='name' target='_blank' href=" . $notice_content['project_url'] . "><?php echo $notice_content['project_title']; ?></a>
                <?php endif; ?>
                <?php echo $this->partial('localcontexts/project.phtml', ['content' => $notice_content]); ?>  
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
</div>
