<div class="local-contexts-multicheckbox-row">
    <div class="drawer">
		<input type="checkbox" name="lc-content[]" aria-labelledby="drawer-title-<?php echo $projectKey; ?>" value="<?php echo html_escape(json_encode($project)); ?>">
		<span class="drawer-name" id="drawer-title-<?php echo $projectKey; ?>"><?php echo $projectTitle; ?></span>
		<button type="button" class="drawer-toggle" data-action-selector="opened" aria-expanded="false" aria-controls="drawer-contents-<?php echo $projectKey; ?>" data-expand-label="<?php echo $this->translate('Show details'); ?>" data-collapse-label="<?php echo $this->translate('Hide details'); ?>" aria-label="<?php echo $this->translate('Show details'); ?>">
			<span class="icon" aria-hidden="true"></span>
		</button>
	</div>
	<div class="drawer-contents" id="drawer-contents-<?php echo $projectKey; ?>">
	    <?php 
    		foreach ($projectByImage as $imageUrl => $notices) {
    			echo $this->partial('lc-notice.phtml', ['imageUrl' => $imageUrl, 'notices' => $notices]);
    		}
    	?>
    <a class="project-name project-link" target="_blank" href="<?php echo $projectUrl; ?>"><?php echo $projectTitle; ?></a>
	</div>
</div>
