<div class='local-contexts-project'>
<?php foreach ($content as $key => $label): ?>
    <?php if (is_int($key)): ?>
    <div class="local-contexts-notice">
        <img class='image' src='<?php echo $label['image_url']; ?>'>
        <div class='local-context-notice-meta'>
            <div class='notice-name'><?php echo $label['name']; ?></div>
            <div class='notice-description'><?php echo $label['text']; ?></div>
        </div>
    </div>
    <?php endif; ?>
<?php endforeach; ?>
</div>