<?php $localContextsContent = $this->lc_content; ?>

<?php if (count($localContextsContent) > 0): ?>
<div id="local-contexts" class="default">
<?php foreach ($localContextsContent as $content): ?>
    <?php echo $this->partial('localcontexts/project.phtml', ['content' => $content]); ?>
    <?php if (isset($content['project_url'])): ?>
        <div class='project-link'>
            <span class='lc'><?php echo __('Local Contexts project link: '); ?></span>
            <a target='_blank' href="<?php echo $content['project_url']; ?>"><?php echo $content['project_title']; ?></a>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
</div>
<?php endif; ?>

<script>
jQuery(document).ready(function() {
    var footer = (jQuery('footer').length > 0) ? jQuery('footer') : jQuery('#footer');
    jQuery('#local-contexts').prependTo(footer).removeClass('default');
});
</script>