<?php $localContextsContent = $this->lc_content; ?>

<?php if (count($localContextsContent) > 0): ?>
<div id="local-contexts-content" class="default">
    <?php foreach ($localContextsContent as $content): ?>
    <div class='local-contexts-project'>
        <?php echo $content['label']; ?>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<script>
jQuery(document).ready(function() {
    var footer = (jQuery('#footer-text > span').length > 0) ? jQuery('#footer-text > span') : jQuery('#footer-text > p');
    jQuery('#footer-text > #local-contexts-content').insertAfter(footer);
});
</script>