<?php $localContextsContent = $this->lc_content; ?>

<?php if (count($localContextsContent) > 0): ?>
<div id="local-contexts-content" class="default">
    <?php foreach ($localContextsContent as $content): ?>
    <div class='local-contexts-project'>
        <?php echo $content['label']; ?>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<script>
jQuery(document).ready(function() {
    var footer = (jQuery('footer').length > 0) ? jQuery('footer') : jQuery('#footer');
    jQuery('#local-contexts').prependTo(footer).removeClass('default');
});
</script>